{% set version = "2.10" %}

package:
  name: tktable
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/tktable/tktable/{{ version }}/Tktable{{ version }}.tar.gz
  sha256: c335117fa1be45fe4d3032e96fd4b4641fff6a4f8467878608dabed11198a4cb
  patches:
    - 0001-Remove-hardcoded-libs.patch
    - 0002-Fix-incompatible-function-pointer-types-add-CONST86.patch
    - 0003-Fix-implicit-function-declaration-for-panic-on-macOS.patch

build:
  number: 6

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - libxcb                             # [linux]
    - xorg-libxau                        # [linux]
    - make                               # [linux]
  host:
    - tk
  run:
    - tk

test:
  commands:
    - echo "exit [catch {package require -exact Tktable {{ version }} }]" | xvfb-run tclsh  # [linux]
    - echo "exit [catch {package require -exact Tktable {{ version }} }]" | tclsh  # [not (linux or win)]
    - echo exit [catch {package require -exact Tktable {{ version }} }] | tclsh  # [win]

about:
  home: http://www.tcl.tk/
  license: TCL
  license_file: license.txt
  summary: Tktable is a 2D editable table widget
  doc_url: https://core.tcl.tk/jenglish/gutter/packages/tktable.html

extra:
  recipe-maintainers:
    - fhoehle
    - xhochy
